name: geo_monitor
description: Gio FrontEnd Apps
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  realm: ^1.1.0
  cupertino_icons: ^1.0.5
  hive: ^2.2.3
  fluttertoast: ^8.2.2
  geofence_service: ^4.0.0
  geocoding: ^2.1.0
  path_provider: ^2.0.13
  provider: ^6.0.5
  material_design_icons_flutter: ^6.0.7096
  intl: ^0.18.0
  http: ^0.13.5
  google_maps_flutter: ^2.2.8
  google_fonts: ^4.0.3
  image: ^4.0.16
  video_thumbnail: ^0.5.3
  android_intent: ^2.0.2
  uuid: ^3.0.7
  #  location: ^4.4.0
  page_transition: ^2.0.9
  responsive_builder: ^0.7.0
  native_device_orientation: ^1.1.4
  google_maps_utils: ^1.5.0+0
  google_maps_cluster_manager: ^3.0.0+1
  get_storage: ^2.1.1
  archive: ^3.3.7
  hive_flutter: ^1.1.0
  flutter_local_notifications: ^13.0.0
  firebase_auth: ^4.6.1
  firebase_messaging: ^14.6.1
  firebase_core: ^2.13.0
  firebase_storage: ^11.2.1
  permission_handler: ^10.2.0
  just_audio: ^0.9.33
  connectivity_plus: ^3.0.0
  maps_toolkit: ^2.0.1
  #  device_info_plus: ^8.1.0
  flex_color_scheme: ^7.1.2
  #  background_location: ^0.8.1
  geolocator: ^9.0.2
  video_player: ^2.6.1
  animations: ^2.0.7
  chewie: ^1.4.0
  #  map_launcher: ^2.5.0+1
  image_picker: ^0.8.7+5
  universal_platform:
  focused_menu: ^1.0.5
  camera: ^0.10.5+2
  badges: ^3.1.1
  cached_network_image: ^3.2.3
  dots_indicator: ^2.1.0
  #  flutter_libphonenumber: ^1.3.0
  firebase_crashlytics: ^3.0.12
  pin_code_fields: ^7.4.0
  animated_splash_screen: ^1.3.0
  font_awesome_flutter: ^10.4.0
  record: ^4.4.4
  mic_stream: ^0.6.5
  audio_waveforms: ^1.0.4
  webview_flutter: ^4.0.7
  shared_preferences: ^2.0.20
  file_picker: ^5.2.9
  #  audioplayers: ^4.0.1
  siri_wave: ^0.3.0
  fl_chart: ^0.61.0
  url_launcher: ^6.1.11
  graphql_flutter: ^5.1.1
  flutter_rating_bar: ^4.0.1
  lat_lng_to_timezone: ^0.2.0
  riverpod_annotation:
  riverpod: ^2.3.6
  flutter_riverpod: ^2.3.6
  json_annotation: ^4.8.1
  googleapis_auth: ^1.4.1
#  realm_common: ^1.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  build_runner: ^2.4.4
  hive_generator:
  mockito: ^5.4.1
  json_serializable: ^6.7.0


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/intro/
    - assets/mapicons/
    - assets/l10n/
    - assets/
    - assets/projects/
    - assets/payment/
